# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= Rails.application.credentials.dig(:development, :postgres, :host) %>
  username: <%= Rails.application.credentials.dig(:development, :postgres, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :postgres, :password) %>
  database: baby_names_development

test:
  <<: *default
  host: <%= Rails.application.credentials.dig(:test, :postgres, :host) %>
  username: <%= Rails.application.credentials.dig(:test, :postgres, :username) %>
  password: <%= Rails.application.credentials.dig(:test, :postgres, :password) %>
  database: baby_names_test

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:production, :postgres, :host) %>
  username: <%= Rails.application.credentials.dig(:production, :postgres, :username) %>
  password: <%= Rails.application.credentials.dig(:production, :postgres, :password) %>
  database: baby_names_production
